
  1%|▍                                                               | 864k/119M [00:00<00:25, 4.81MB/s]


























100%|████████████████████████████████████████████████████████████████| 119M/119M [00:52<00:00, 2.35MB/s]
Traceback (most recent call last):
  File "train.py", line 625, in <module>
    main(opt)
  File "train.py", line 522, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 115, in train
    ckpt = torch.load(weights, map_location=device)  # load checkpoint
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/serialization.py", line 851, in _load
    result = unpickler.load()
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/serialization.py", line 843, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/serialization.py", line 832, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/serialization.py", line 812, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/serialization.py", line 157, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/_utils.py", line 80, in _cuda
    return new_type(self.size()).copy_(self, non_blocking)
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/cuda/__init__.py", line 484, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: out of memory